// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUUIouxO6rAH1JD_Ju2rqJcnTZSdppJ8g',
    appId: '1:503517406285:web:c8d22b0b9a42c33218a804',
    messagingSenderId: '503517406285',
    projectId: 'recipedia-e9f8e',
    authDomain: 'recipedia-e9f8e.firebaseapp.com',
    storageBucket: 'recipedia-e9f8e.firebasestorage.app',
    measurementId: 'G-DXB5XNKTRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh6_rUeYCC2VkaCrS7Y8WlMbRkv3411vM',
    appId: '1:503517406285:android:e9fbb2c2634064cd18a804',
    messagingSenderId: '503517406285',
    projectId: 'recipedia-e9f8e',
    storageBucket: 'recipedia-e9f8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6yzpg1RmSpcOD1_AkwrHFeupit7-zVQU',
    appId: '1:503517406285:ios:68e9dc7713d7c5fc18a804',
    messagingSenderId: '503517406285',
    projectId: 'recipedia-e9f8e',
    storageBucket: 'recipedia-e9f8e.firebasestorage.app',
    iosBundleId: 'com.example.recipedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6yzpg1RmSpcOD1_AkwrHFeupit7-zVQU',
    appId: '1:503517406285:ios:68e9dc7713d7c5fc18a804',
    messagingSenderId: '503517406285',
    projectId: 'recipedia-e9f8e',
    storageBucket: 'recipedia-e9f8e.firebasestorage.app',
    iosBundleId: 'com.example.recipedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUUIouxO6rAH1JD_Ju2rqJcnTZSdppJ8g',
    appId: '1:503517406285:web:77914f0b3e74e52f18a804',
    messagingSenderId: '503517406285',
    projectId: 'recipedia-e9f8e',
    authDomain: 'recipedia-e9f8e.firebaseapp.com',
    storageBucket: 'recipedia-e9f8e.firebasestorage.app',
    measurementId: 'G-GW759JB6PG',
  );
}
